// <auto-generated />
using System;
using InventoryManagerDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagerDatabase.Migrations
{
    [DbContext(typeof(InventoryManagerContext))]
    partial class InventoryManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryManagerDatabase.model.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Height");

                    b.Property<int>("Length");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("InventoryManagerDatabase.model.pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Isplacede");

                    b.Property<decimal>("Weight");

                    b.Property<int?>("sizeId");

                    b.HasKey("Id");

                    b.HasIndex("sizeId");

                    b.ToTable("pallets");
                });

            modelBuilder.Entity("InventoryManagerDatabase.model.pallet", b =>
                {
                    b.HasOne("InventoryManagerDatabase.model.Size", "size")
                        .WithMany()
                        .HasForeignKey("sizeId");
                });
#pragma warning restore 612, 618
        }
    }
}
